//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiket_reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tgl_pesan
    {
        public string prefix { get; set; }
        public int id_pembeli { get; set; }
        public string nm_pembeli { get; set; }
        public string tgl_order { get; set; }
    }
}
